20 create g code module
BAMresearch/amworkflow pull request #23
Opened 2023-11-22 12:45 UTC by YuXHe15

+ Add main class Gcode which is an interface to all g-code functions.
+  add a submodule "utils", which contain functions and classes working for Gcode Class:
     + PrintState: an Enum class, which defines semantic printer states, which will contain G-Codes from different standards.
     + create_new_config: a function for creating a new config file (YAML) by exporting all printer states to a YAML file.
     + read_config: read config file under /config dir by specified standard name.
     + GcodeCommand: A class which serve to translate semantic command to G-Code and handle all kinds of basic jobs like formatting, initializing, file-output, standard-loading, working as a lower level function compared to Gcode Class.
+ Add a folder: calibration. for now there is only one report I wrote which documented the way I calibrated the printer. The related codes will be added later.

2023-11-23 14:01 UTC, aradermacher commented on tests/test_gcode.py
Very good that you wrote a test. 
Could you integrate the gcode task also in one of the examples (Wall or TrussArc [I think that is more complicated because it isn't a closed loop] )

2023-11-23 14:09 UTC, aradermacher commented on .DS_Store
What is that?

2023-11-23 14:13 UTC, aradermacher commented on amworkflow/gcode/calibration/report-first-run-20231115.md
I would like to move those explanations in a different directory and linking it in the main readme. Let's discuss

2023-11-23 14:15 UTC, aradermacher commented on amworkflow/gcode/example.gcode
Do we need this file here?

2023-12-11 12:23 UTC, YuXHe15 commented
All unnecessary files have been deleted. The Gcode Class now is the base class and the class I am working on is GcodeFromPoints(Gcode) as we discussed. One new features is included, which logs info of the model in the gcode as comments, as well as an estimated material volume consumption.
/ #23

2023-12-13 12:19 UTC, aradermacher requested changes
Thanks for the changes. Why are the actions not running?

2023-12-13 13:34 UTC, aradermacher approved these changes
if all action (beside arc) are running and the randompoint example is merged with the gcode_test you can merge the branch

2023-12-13 13:38 UTC, merged